DROP TABLE IF EXISTS CONTACT_DETAILS;
CREATE TABLE CONTACT_DETAILS(CONTACT_ID NUMBER(10) PRIMARY KEY, CONTACT_NAME VARCHAR2(50),CONTACT_EMAIL VARCHAR2(50),CONTACT_NUMBER NUMBER(10));
INSERT INTO  CONTACT_DETAILS VALUES(1, 'ALEEM SHAIK','skaleeminfo@gmail.com',8886088870);
INSERT INTO  CONTACT_DETAILS VALUES(2, 'SAMEENA SHAIK','sksameenainfo@gmail.com',8886088860);
SELECT * FROM CONTACT_DETAILS ORDER BY CONTACT_ID;
UPDATE CONTACT_DETAILS SET CONTACT_NAME='ABDUL ALEEM SHAIK' WHERE CONTACT_ID=1;
DELETE FROM CONTACT_DETAILS WHERE CONTACT_ID=2;
SELECT * FROM CONTACT_DETAILS ORDER BY CONTACT_ID;