DROP TABLE IF EXISTS CONTACT;
CREATE TABLE CONTACT(ID NUMBER(10) PRIMARY KEY,NAME VARCHAR2(50),NUMBER NUMBER(10),EMAIL VARCHAR2(50),ACTIVE_SW VARCHAR2(1),CREATED_DATE DATE,UPDATED_DATE DATE);

SELECT * FROM CONTACT ORDER BY ID;
UPDATE CONTACT SET NAME='ABDUL ALEEM SHAIK' WHERE ID=2;
DELETE FROM CONTACT WHERE ID=4;
SELECT * FROM CONTACT ORDER BY ID;